const EXAM_DURATION_MINUTES = 45;

module.exports = {
  EXAM_DURATION_MINUTES,
  EXAM_DURATION_SECONDS: EXAM_DURATION_MINUTES * 60,
  DEFAULT_PASSING_MARKS: 15,
  DEFAULT_TOTAL_QUESTIONS: 25,
  COURSE_NAME: "AI & Robotics Examination",
  RESULT_STATUS: {
    PASS: "Pass",
    FAIL: "Fail"
  }
};
